site_name: Отчет по лабораторным работам
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Lab 1:
      - Body: lab1/body.md
      - Screens: lab1/screens.md
  - Lab 2:
      - Task 1: lab2/task1.md
      - Task 2: lab2/task2.md