# site_name: Отчет по лабораторным работам
# theme:
#   name: readthedocs
# nav:
#   - Лабораторная №1:
#       - Code part: lab1/body.md
#       - Screenshots: lab1/screens.md


site_name: Отчет по лабораторным работам
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Lab 1:
      - Body: lab1/body.md
      - Screens: lab1/screens.md